### ISSUE TITLE
Automate posting a tweet with a link to each new episode on twitter

### ISSUE THREAD

**Issue by hipstersmoothie** [devtools-fm/devtools.fm#11]

**Comment by zephraph** [comment]
My general thoughts about how to tackle this so far:
1. Use the [feed hive twitter aip](https://github.com/FeedHive/twitter-api-client) to actually interface with twitter
2. Add a github action step that tweets out the link when a new episode file is committed to the `/episodes` directory in `main`

Pre-steps:
1. Add twitter API key to GitHub secrets
