### ISSUE TITLE
Feed for the site itself?

### ISSUE THREAD

**Issue by rauschma** [devtools-fm/devtools.fm#227]
If you have time and energy – I’d find a feed (RSS, Atom or JSON Feed) for the website itself useful:

* When it comes to linking to episodes, I like the website’s pages best – e.g.: https://www.devtools.fm/episode/70
* In contrast, the RSS feed on the start page links to (e.g.): https://podcasters.spotify.com/pod/show/devtoolsfm/episodes/Emanuele-Stoppa---Biome-e2akb29

(Feel free to close this issue if that‘s not something you want to do.)

**Comment by hipstersmoothie** [comment]
Available at `https://devtools.fm/rss.xml` (once the deploy finishes)

**Comment by rauschma** [comment]
Great, thanks! Feed auto-discovery can help with finding that feed: https://dri.es/rss-auto-discovery

```html
<link rel="alternate" type="application/rss+xml" title="Dries Buytaert" href="https: //dri.es/rss.xml" />
```

With this tag in the head of a web page, feed readers will find the feed if someone enters the URL of the web page.
